# Generated by Django 5.1.1 on 2024-10-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_board_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='작성자 이름'),
        ),
    ]
