# Generated by Django 5.1 on 2024-09-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_board_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='contexts',
            new_name='contents',
        ),
    ]
